platform :ios, '9.0'

target 'FBLA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FBLA
	pod 'KDCalendar', '~> 1.8.9'

end
